CREATE TABLE [dbo].[CBO_OCUPACOES] (
    [ID_OCUPACAO]       NUMERIC (18)   NOT NULL,
    [ID_FAMILIA]        NUMERIC (18)   NOT NULL,
    [DESCRICAO]         NVARCHAR (300) NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50)  NULL,
    [DATA_INCLUSAO]     DATE           NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)  NULL,
    [DATA_ALTERACAO]    DATE           NULL,
    [EXCLUIDO]          INT            NULL
);

