CREATE TABLE [dbo].[ENDERECOS_COMPLEMENTO] (
    [ID_COMPLEMENTO]    NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ID_ENDERECO]       NUMERIC (18)   NOT NULL,
    [DESCRICAO]         NVARCHAR (300) NOT NULL,
    [DATA_INCLUSAO]     DATE           NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)  NULL,
    [DATA_ALTERACAO]    DATE           NULL,
    [EXCLUIDO]          INT            NULL
);

