CREATE TABLE [dbo].[ESCOLARIDADE_NIVEL] (
    [ID_NIVEL_ESCOLARIDADE] NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [DESCRICAO]             NVARCHAR (50) NOT NULL,
    [USUARIO_INCLUSAO]      NVARCHAR (50) NULL,
    [DATA_INCLUSAO]         DATE          NULL,
    [USUARIO_ALTERACAO]     NVARCHAR (50) NULL,
    [DATA_ALTERACAO]        DATE          NULL,
    [EXCLUIDO]              INT           NULL
);



