CREATE TABLE [dbo].[MENU_OPCAO_PERFIL] (
    [ID_MENU_OPC_PER]   NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [ID_MENU_OPC]       NUMERIC (18)  NOT NULL,
    [ID_PERFIL]         NUMERIC (18)  NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50) NULL,
    [DATA_INCLUSAO]     DATE          NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50) NULL,
    [DATA_ALTERACAO]    DATE          NULL,
    [EXCLUIDO]          INT           NULL
);

