CREATE TABLE [dbo].[MENU_OPCOES] (
    [ID_MENU_OPC]       NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME_MEN]          VARCHAR (60)  NOT NULL,
    [PASTA_MEN]         VARCHAR (60)  NOT NULL,
    [CONTROLADOR_MEN]   VARCHAR (60)  NOT NULL,
    [ACAO_MEN]          VARCHAR (60)  NOT NULL,
    [ICONE_MEN]         VARCHAR (60)  NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50) NULL,
    [DATA_INCLUSAO]     DATE          NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50) NULL,
    [DATA_ALTERACAO]    DATE          NULL,
    [EXCLUIDO]          INT           NULL
);

