/*CREATE TABLE [dbo].[MNU_FUNCAO] (
    [ID]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [NOME]      NVARCHAR (255) NULL,
    [DESCRICAO] NVARCHAR (255) NULL,
    [IMAGEM]    NVARCHAR (255) NULL,
    [PAGINA]    NVARCHAR (255) NULL,
    [JS]        NVARCHAR (255) NULL,
    [SEPARADOR] NUMERIC (18)   NULL,
    [ID_FUNCAO] NUMERIC (18)   NULL,
    [ORDEM]     NUMERIC (18)   NULL,
    [NIVEL]     NUMERIC (18)   NULL,
    [EXCLUIDO]  NUMERIC (18)   NULL
);*/

