CREATE TABLE [dbo].[PERFIS] (
    [ID_PERFIL]         NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (30) NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50) NULL,
    [DATA_INCLUSAO]     DATE          NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50) NULL,
    [DATA_ALTERACAO]    DATE          NULL,
    [EXCLUIDO]          INT           NULL
);



