CREATE TABLE [dbo].[QUESTIONARIOS] (
    [ID_QUESTIONARIO]   NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50)  NOT NULL,
    [DESCRICAO]         NVARCHAR (300) NULL,
    [INSTRUCAO]         TEXT           NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50)  NULL,
    [DATA_INCLUSAO]     DATE           NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)  NULL,
    [DATA_ALTERACAO]    DATE           NULL,
    [EXCLUIDO]          INT            NULL
);





