ALTER TABLE [dbo].[CBO_SUB_GRUPOS]
    ADD CONSTRAINT [FK_CBO_SUB_GRUPO_CBO_SUB_GRUPO_PRINCIPAL] FOREIGN KEY ([ID_SUB_GRUPO_PRINCIPAL]) REFERENCES [dbo].[CBO_SUB_GRUPOS_PRINCIPAIS] ([ID_SUB_GRUPO_PRINCIPAL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

