ALTER TABLE [dbo].[CBO_OCUPACOES]
    ADD CONSTRAINT [FK_CBO_OCUPACOES_CBO_FAMILIAS] FOREIGN KEY ([ID_FAMILIA]) REFERENCES [dbo].[CBO_FAMILIAS] ([ID_FAMILIA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

