/*ALTER TABLE [dbo].[CBO_SUB_GRUPO_PRINCIPAL]
    ADD CONSTRAINT [FK_CBO_SUB_GRUPO_PRINCIPAL_CBO_GRUPO] FOREIGN KEY ([ID_GRUPO]) REFERENCES [dbo].[CBO_GRUPO] ([ID_GRUPO]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

