/*ALTER TABLE [dbo].[CUPONS_USUARIO]
    ADD CONSTRAINT [FK_CUPONS_USUARIO_CUPONS_CREDITO] FOREIGN KEY ([ID_CUPONS]) REFERENCES [dbo].[CUPONS_CREDITO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

