ALTER TABLE [dbo].[CBO_SUB_GRUPOS_PRINCIPAIS]
    ADD CONSTRAINT [FK_CBO_SUB_GRUPO_PRINCIPAL_CBO_GRUPO] FOREIGN KEY ([ID_GRUPO]) REFERENCES [dbo].[CBO_GRUPOS] ([ID_GRUPO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

