ALTER TABLE [dbo].[ENDERECOS_COMPLEMENTO]
    ADD CONSTRAINT [FK_ENDERECOS_COMPLEMENTO_ENDERECOS_COMPLEMENTO] FOREIGN KEY ([ID_ENDERECO]) REFERENCES [dbo].[ENDERECOS] ([ID_ENDERECO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

