ALTER TABLE [dbo].[ESCOLARIDADE]
    ADD CONSTRAINT [FK_ESCOLARIDADE_ESCOLARIDADE_NIVEL] FOREIGN KEY ([ID_NIVEL_ESCOLARIDADE]) REFERENCES [dbo].[ESCOLARIDADE_NIVEL] ([ID_NIVEL_ESCOLARIDADE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

