/*ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO]
    ADD CONSTRAINT [FK_MNU_GRUPO_FUNCAO_MNU_FUNCAO] FOREIGN KEY ([ID_MNU_FUNCAO]) REFERENCES [dbo].[MNU_FUNCAO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

