/*ALTER TABLE [dbo].[MENU_OPCAO_PERFIL]
    ADD CONSTRAINT [FK_MENU_OPCAO_PERFIL_MENU_OPCAO_PERFIL] FOREIGN KEY ([ID_MENU_OPC]) REFERENCES [dbo].[MENU_OPCOES] ([ID_MENU_OPC]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

