ALTER TABLE [dbo].[OPCOES_RESPOSTA_QUESTIONARIOS]
    ADD CONSTRAINT [FK_OPCAO_RESPOSTA_QUESTIONARIO_OPCOES_RESPOSTA] FOREIGN KEY ([ID_OPCAO_RESPOSTA]) REFERENCES [dbo].[OPCOES_RESPOSTA] ([ID_OPCAO_RESPOSTA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

