/*ALTER TABLE [dbo].[PRODUTO_CARACTERISTICA]
    ADD CONSTRAINT [FK_PRODUTO_CARACTERISTICA_PRODUTO_SUB_TIPO] FOREIGN KEY ([ID_SUB_TIPO]) REFERENCES [dbo].[PRODUTO_SUB_TIPO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

