/*ALTER TABLE [dbo].[PRODUTO_SUB_TIPO]
    ADD CONSTRAINT [FK_PRODUTO_SUB_TIPO_PRODUTO_TIPO] FOREIGN KEY ([ID_TIPO]) REFERENCES [dbo].[PRODUTO_TIPO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

