ALTER TABLE [dbo].[QUESTOES_QUESTIONARIOS]
    ADD CONSTRAINT [FK_QUESTOES_QUESTIONARIOS_QUESTOES_QUESTIONARIOS] FOREIGN KEY ([ID_QUESTAO]) REFERENCES [dbo].[QUESTOES] ([ID_QUESTAO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

