ALTER TABLE [dbo].[QUESTOES_QUESTIONARIOS]
    ADD CONSTRAINT [FK_QUESTOES_QUESTIONARIOS_QUESTIONARIOS] FOREIGN KEY ([ID_QUESTIONARIO]) REFERENCES [dbo].[QUESTIONARIOS] ([ID_QUESTIONARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

