/*ALTER TABLE [dbo].[QUESTOES_GRUPOS]
    ADD CONSTRAINT [FK_QUESTOES_GRUPOS_QUESTOES] FOREIGN KEY ([ID_QUESTAO]) REFERENCES [dbo].[QUESTOES] ([ID_QUESTAO]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

