/*ALTER TABLE [dbo].[QUESTOES]
    ADD CONSTRAINT [FK_QUESTOES_QUESTIONARIOS] FOREIGN KEY ([ID_QUESTIONARIO]) REFERENCES [dbo].[QUESTIONARIOS] ([ID_QUESTIONARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

