/*ALTER TABLE [dbo].[RESPOSTAS]
    ADD CONSTRAINT [FK_RESPOSTAS_QUESTIONARIOS] FOREIGN KEY ([ID_QUESTIONARIO]) REFERENCES [dbo].[QUESTIONARIOS] ([ID_QUESTIONARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

