ALTER TABLE [dbo].[RELATORIOS]
    ADD CONSTRAINT [FK_RELATORIOS_QUESTOES_GRUPOS] FOREIGN KEY ([ID_GRUPO]) REFERENCES [dbo].[RELATORIOS_GRUPOS] ([ID_GRUPO]) ON DELETE NO ACTION ON UPDATE NO ACTION;





