/*ALTER TABLE [dbo].[RESPOSTAS]
    ADD CONSTRAINT [FK_RESPOSTAS_OPCAO_RESPOSTA_QUESTIONARIO] FOREIGN KEY ([ID_OPCAO_RESPOSTA_QUESTIONARIO]) REFERENCES [dbo].[OPCAO_RESPOSTA_QUESTIONARIO] ([ID_OPCAO_RESPOSTA_QUESTIONARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

