ALTER TABLE [dbo].[RESULTADOS]
    ADD CONSTRAINT [FK_RESULTADOS_QUESTIONARIOS] FOREIGN KEY ([ID_QUESTIONARIO]) REFERENCES [dbo].[QUESTIONARIOS] ([ID_QUESTIONARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

