ALTER TABLE [dbo].[USUARIOS_QUESTIONARIOS]
    ADD CONSTRAINT [FK_USUARIOS_QUESTIONARIOS_USUARIOS] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIOS] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

