ALTER TABLE [dbo].[CBO_SINONIMOS]
    ADD CONSTRAINT [PK_CBO_SINONIMOS] PRIMARY KEY CLUSTERED ([ID_SINONIMO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

