ALTER TABLE [dbo].[CBO_SUB_GRUPOS_PRINCIPAIS]
    ADD CONSTRAINT [PK_CBO_SUB_GRUPO_PRINCIPAL] PRIMARY KEY CLUSTERED ([ID_SUB_GRUPO_PRINCIPAL] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

