ALTER TABLE [dbo].[CBO_FAMILIAS]
    ADD CONSTRAINT [PK_CBO_FAMILIA] PRIMARY KEY CLUSTERED ([ID_FAMILIA] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

