/*ALTER TABLE [dbo].[CBO_SUB_GRUPO]
    ADD CONSTRAINT [PK_CBO_SUB_GRUPO] PRIMARY KEY CLUSTERED ([ID_SUB_GRUPO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

