ALTER TABLE [dbo].[CBO_OCUPACOES]
    ADD CONSTRAINT [PK_CBO_OCUPACOES] PRIMARY KEY CLUSTERED ([ID_OCUPACAO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

