ALTER TABLE [dbo].[ENDERECOS_COMPLEMENTO]
    ADD CONSTRAINT [PK_ENDERECOS_COMPLEMENTO] PRIMARY KEY CLUSTERED ([ID_COMPLEMENTO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

