ALTER TABLE [dbo].[ESCOLARIDADE]
    ADD CONSTRAINT [PK_ESCOLARIDADE] PRIMARY KEY CLUSTERED ([ID_ESCOLARIDADE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

