ALTER TABLE [dbo].[ESTADO_CIVIL]
    ADD CONSTRAINT [PK_ESTADO_CIVIL] PRIMARY KEY CLUSTERED ([ID_ESTADO_CIVIL] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

