ALTER TABLE [dbo].[ESCOLARIDADE_NIVEL]
    ADD CONSTRAINT [PK_ESCOLARIDADE_NIVEL] PRIMARY KEY CLUSTERED ([ID_NIVEL_ESCOLARIDADE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

