ALTER TABLE [dbo].[ESTADOS]
    ADD CONSTRAINT [PK_ESTADOS] PRIMARY KEY CLUSTERED ([ID_ESTADO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

