ALTER TABLE [dbo].[ENDERECOS]
    ADD CONSTRAINT [PK_ENDERECO] PRIMARY KEY CLUSTERED ([ID_ENDERECO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

