ALTER TABLE [dbo].[RELATORIOS]
    ADD CONSTRAINT [PK_LAUDOS] PRIMARY KEY CLUSTERED ([ID_RELATORIO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

