ALTER TABLE [dbo].[MENU_OPCAO_PERFIL]
    ADD CONSTRAINT [PK_MENU_OPCAO_PERFIL] PRIMARY KEY CLUSTERED ([ID_MENU_OPC_PER] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

