ALTER TABLE [dbo].[MUNICIPIOS]
    ADD CONSTRAINT [PK_MUNICIPIOS] PRIMARY KEY CLUSTERED ([ID_MUNICIPIO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

