ALTER TABLE [dbo].[NIVEL_RESULTADO]
    ADD CONSTRAINT [PK_NIVEL_RESULTADO] PRIMARY KEY CLUSTERED ([ID_NIVEL] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

