ALTER TABLE [dbo].[MENU_OPCOES]
    ADD CONSTRAINT [PK_OPCOES] PRIMARY KEY CLUSTERED ([ID_MENU_OPC] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

