/*ALTER TABLE [dbo].[OPCAO_RESPOSTA_QUESTIONARIO]
    ADD CONSTRAINT [PK_OPCAO_RESPOSTA_QUESTIONARIO] PRIMARY KEY CLUSTERED ([ID_OPCAO_RESPOSTA_QUESTIONARIO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

