ALTER TABLE [dbo].[OPCOES_RESPOSTA_QUESTIONARIOS]
    ADD CONSTRAINT [PK_OPCAO_RESPOSTA_QUESTIONARIO] PRIMARY KEY CLUSTERED ([ID_OPCAO_RESPOSTA_QUESTIONARIO] ASC, [ID_OPCAO_RESPOSTA] ASC, [ID_QUESTIONARIO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

