ALTER TABLE [dbo].[PESSOAS]
    ADD CONSTRAINT [PK_PESSOAS] PRIMARY KEY CLUSTERED ([ID_PESSOA] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

