ALTER TABLE [dbo].[PERFIS]
    ADD CONSTRAINT [PK_PERFIS] PRIMARY KEY CLUSTERED ([ID_PERFIL] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

