ALTER TABLE [dbo].[QUESTOES]
    ADD CONSTRAINT [PK_QUESTOES] PRIMARY KEY CLUSTERED ([ID_QUESTAO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

