ALTER TABLE [dbo].[QUESTIONARIOS]
    ADD CONSTRAINT [PK_QUESTIONARIOS] PRIMARY KEY CLUSTERED ([ID_QUESTIONARIO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

