ALTER TABLE [dbo].[QUESTOES_QUESTIONARIOS]
    ADD CONSTRAINT [PK_QUESTOES_QUESTIONARIOS] PRIMARY KEY CLUSTERED ([ID_QUESTAO_QUESTIONARIO] ASC, [ID_QUESTAO] ASC, [ID_QUESTIONARIO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

