ALTER TABLE [dbo].[RESULTADOS]
    ADD CONSTRAINT [PK_RESULTADO] PRIMARY KEY CLUSTERED ([ID_RESULTADO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

