ALTER TABLE [dbo].[RESPOSTAS]
    ADD CONSTRAINT [PK_RESPOSTAS] PRIMARY KEY CLUSTERED ([ID_RESPOSTA] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

