/*ALTER TABLE [dbo].[PRODUTO]
    ADD CONSTRAINT [FK_PRODUTO_PRODUTO_CARACTERISTICA] FOREIGN KEY ([ID_CARACTERISTICA]) REFERENCES [dbo].[PRODUTO_CARACTERISTICA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

