/*ALTER TABLE [dbo].[PRODUTO_CARACTERISTICA]
    ADD CONSTRAINT [FK_PRODUTO_CARACTERISTICA_PRODUTO] FOREIGN KEY ([ID_PRODUTO]) REFERENCES [dbo].[PRODUTO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;*/

