/*
Deployment script for LEVIVIER
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "LEVIVIER"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
USE [master]
GO
IF (DB_ID(N'$(DatabaseName)') IS NOT NULL
    AND DATABASEPROPERTYEX(N'$(DatabaseName)','Status') <> N'ONLINE')
BEGIN
    RAISERROR(N'The state of the target database, %s, is not set to ONLINE. To deploy to this database, its state must be set to ONLINE.', 16, 127,N'$(DatabaseName)') WITH NOWAIT
    RETURN
END

GO

IF NOT EXISTS (SELECT 1 FROM [master].[dbo].[sysdatabases] WHERE [name] = N'$(DatabaseName)')
BEGIN
    RAISERROR(N'You cannot deploy this update script to target TI029727GO\SQLEXPRESS. The database for which this script was built, LEVIVIER, does not exist on this server.', 16, 127) WITH NOWAIT
    RETURN
END

GO

IF (@@servername != 'TI029727GO\SQLEXPRESS')
BEGIN
    RAISERROR(N'The server name in the build script %s does not match the name of the target server %s. Verify whether your database project settings are correct and whether your build script is up to date.', 16, 127,N'TI029727GO\SQLEXPRESS',@@servername) WITH NOWAIT
    RETURN
END

GO

IF CAST(DATABASEPROPERTY(N'$(DatabaseName)','IsReadOnly') as bit) = 1
BEGIN
    RAISERROR(N'You cannot deploy this update script because the database for which it was built, %s , is set to READ_ONLY.', 16, 127, N'$(DatabaseName)') WITH NOWAIT
    RETURN
END

GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)]
GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

GO
PRINT N'Creating [dbo].[AMIGOS]...';


GO
CREATE TABLE [dbo].[AMIGOS] (
    [ID]         NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [ID_USUARIO] NUMERIC (18)  NOT NULL,
    [NOME]       NVARCHAR (50) NOT NULL,
    [EMAIL]      NVARCHAR (50) NOT NULL
);


GO
PRINT N'Creating PK_AMIGOS...';


GO
ALTER TABLE [dbo].[AMIGOS]
    ADD CONSTRAINT [PK_AMIGOS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[CAMPANHA]...';


GO
CREATE TABLE [dbo].[CAMPANHA] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50) NOT NULL,
    [ID_EMPRESA]        NUMERIC (18)  NOT NULL,
    [IMAGEM]            NVARCHAR (50) NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50) NULL,
    [DATA_INCLUSAO]     DATE          NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50) NULL,
    [DATA_ALTERACAO]    DATE          NULL,
    [EXCLUIDO]          INT           NULL
);


GO
PRINT N'Creating PK_CAMPANHA...';


GO
ALTER TABLE [dbo].[CAMPANHA]
    ADD CONSTRAINT [PK_CAMPANHA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[CARRINHO]...';


GO
CREATE TABLE [dbo].[CARRINHO] (
    [ID]                NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [ID_USUARIO]        NUMERIC (18)    NOT NULL,
    [ID_PRODUTO]        NUMERIC (18)    NOT NULL,
    [ID_CAMPANHA]       NUMERIC (18)    NOT NULL,
    [QTD]               INT             NOT NULL,
    [VALOR_UNITARIO]    NUMERIC (18, 2) NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30)   NULL,
    [DATA_INCLUSAO]     DATETIME        NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30)   NULL,
    [DATA_ALTERACAO]    DATETIME        NULL,
    [EXCLUIDO]          INT             NULL
);


GO
PRINT N'Creating PK_CARRINHO...';


GO
ALTER TABLE [dbo].[CARRINHO]
    ADD CONSTRAINT [PK_CARRINHO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[CIDADES]...';


GO
CREATE TABLE [dbo].[CIDADES] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [UF]                CHAR (2)      NOT NULL,
    [NOME]              NVARCHAR (30) NOT NULL,
    [ID_REGIAO]         NUMERIC (18)  NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30) NULL,
    [DATA_INCLUSAO]     DATETIME      NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30) NULL,
    [DATA_ALTERACAO]    DATETIME      NULL,
    [EXCLUIDO]          INT           NULL
);


GO
PRINT N'Creating PK_CIDADES...';


GO
ALTER TABLE [dbo].[CIDADES]
    ADD CONSTRAINT [PK_CIDADES] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[CONTATO]...';


GO
CREATE TABLE [dbo].[CONTATO] (
    [ID]                NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [CPF]               NVARCHAR (14)   NULL,
    [NOME]              NVARCHAR (255)  NULL,
    [RG]                NVARCHAR (30)   NULL,
    [ORGAO_EXPEDIDOR]   NVARCHAR (30)   NULL,
    [TELEFONE1]         NVARCHAR (14)   NULL,
    [CELULAR1]          NVARCHAR (14)   NULL,
    [EMAIL1]            NVARCHAR (255)  NULL,
    [TELEFONE2]         NVARCHAR (14)   NULL,
    [CELULAR2]          NVARCHAR (14)   NULL,
    [EMAIL2]            NVARCHAR (255)  NULL,
    [OBS]               NVARCHAR (1024) NULL,
    [PRINCIPAL]         NUMERIC (18)    NULL,
    [ID_EMPRESA]        NUMERIC (18)    NULL,
    [ID_TIPO_CONTATO]   NUMERIC (18)    NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30)   NULL,
    [DATA_INCLUSAO]     DATETIME        NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30)   NULL,
    [DATA_ALTERACAO]    DATETIME        NULL,
    [EXCLUIDO]          NUMERIC (18)    NULL
);


GO
PRINT N'Creating PK_CONTATO...';


GO
ALTER TABLE [dbo].[CONTATO]
    ADD CONSTRAINT [PK_CONTATO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[CUPONS_CREDITO]...';


GO
CREATE TABLE [dbo].[CUPONS_CREDITO] (
    [ID]                NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [DESCRICAO]         NVARCHAR (50)   NOT NULL,
    [VALOR]             NUMERIC (18, 2) NOT NULL,
    [DATA_VALIDADE]     DATETIME        NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30)   NULL,
    [DATA_INCLUSAO]     DATETIME        NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30)   NULL,
    [DATA_ALTERACAO]    DATETIME        NULL,
    [EXCLUIDO]          INT             NULL
);


GO
PRINT N'Creating PK_CUPONS_CREDITO...';


GO
ALTER TABLE [dbo].[CUPONS_CREDITO]
    ADD CONSTRAINT [PK_CUPONS_CREDITO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[CUPONS_USUARIO]...';


GO
CREATE TABLE [dbo].[CUPONS_USUARIO] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [ID_USUARIO]        NUMERIC (18)  NOT NULL,
    [ID_CUPONS]         NUMERIC (18)  NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30) NULL,
    [DATA_INCLUSAO]     DATETIME      NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30) NULL,
    [DATA_ALTERACAO]    DATETIME      NULL,
    [EXCLUIDO]          INT           NULL
);


GO
PRINT N'Creating PK_CUPONS_USUARIO...';


GO
ALTER TABLE [dbo].[CUPONS_USUARIO]
    ADD CONSTRAINT [PK_CUPONS_USUARIO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[EMPRESA]...';


GO
CREATE TABLE [dbo].[EMPRESA] (
    [ID]                 NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [RAZAO_SOCIAL]       NVARCHAR (255)  NULL,
    [NOME_FANTASIA]      NVARCHAR (255)  NULL,
    [CNPJ]               NVARCHAR (18)   NULL,
    [INSCRICAO_ESTADUAL] NVARCHAR (50)   NULL,
    [ENDERECO]           NVARCHAR (255)  NULL,
    [COMPLEMENTO]        NVARCHAR (127)  NULL,
    [BAIRRO]             NVARCHAR (127)  NULL,
    [CEP]                NVARCHAR (9)    NULL,
    [MUNICIPIO]          NVARCHAR (127)  NULL,
    [MARGEM_COMERCIAL]   NUMERIC (10, 2) NULL,
    [ID_CIDADE]          NUMERIC (18)    NULL,
    [ID_RAMO_NEGOCIO]    NUMERIC (18)    NULL,
    [USUARIO_INCLUSAO]   NVARCHAR (30)   NULL,
    [DATA_INCLUSAO]      DATETIME        NULL,
    [USUARIO_ALTERACAO]  NVARCHAR (30)   NULL,
    [DATA_ALTERACAO]     DATETIME        NULL,
    [EXCLUIDO]           NUMERIC (18)    NULL
);


GO
PRINT N'Creating PK_EMPRESA...';


GO
ALTER TABLE [dbo].[EMPRESA]
    ADD CONSTRAINT [PK_EMPRESA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[MARCAS]...';


GO
CREATE TABLE [dbo].[MARCAS] (
    [ID]                NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (100) NOT NULL,
    [DESCRICAO]         TEXT           NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50)  NULL,
    [DATA_INCLUSAO]     DATE           NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)  NULL,
    [DATA_ALTERACAO]    DATE           NULL,
    [EXCLUIDO]          INT            NULL
);


GO
PRINT N'Creating PK_MARCAS...';


GO
ALTER TABLE [dbo].[MARCAS]
    ADD CONSTRAINT [PK_MARCAS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[MNU_FUNCAO]...';


GO
CREATE TABLE [dbo].[MNU_FUNCAO] (
    [ID]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [NOME]      NVARCHAR (255) NULL,
    [DESCRICAO] NVARCHAR (255) NULL,
    [IMAGEM]    NVARCHAR (255) NULL,
    [PAGINA]    NVARCHAR (255) NULL,
    [JS]        NVARCHAR (255) NULL,
    [SEPARADOR] NUMERIC (18)   NULL,
    [ID_FUNCAO] NUMERIC (18)   NULL,
    [ORDEM]     NUMERIC (18)   NULL,
    [NIVEL]     NUMERIC (18)   NULL,
    [EXCLUIDO]  NUMERIC (18)   NULL
);


GO
PRINT N'Creating PK_MNU_FUNCAO...';


GO
ALTER TABLE [dbo].[MNU_FUNCAO]
    ADD CONSTRAINT [PK_MNU_FUNCAO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[MNU_GRUPO]...';


GO
CREATE TABLE [dbo].[MNU_GRUPO] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50) NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30) NULL,
    [DATA_INCLUSAO]     DATETIME      NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30) NULL,
    [DATA_ALTERACAO]    DATETIME      NULL,
    [EXCLUIDO]          NUMERIC (18)  NULL
);


GO
PRINT N'Creating PK_MNU_GRUPO...';


GO
ALTER TABLE [dbo].[MNU_GRUPO]
    ADD CONSTRAINT [PK_MNU_GRUPO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[MNU_GRUPO_FUNCAO]...';


GO
CREATE TABLE [dbo].[MNU_GRUPO_FUNCAO] (
    [ID]            NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [ID_MNU_GRUPO]  NUMERIC (18) NULL,
    [ID_MNU_FUNCAO] NUMERIC (18) NULL,
    [INC]           NUMERIC (18) NULL,
    [ALT]           NUMERIC (18) NULL,
    [EXC]           NUMERIC (18) NULL
);


GO
PRINT N'Creating PK_MNU_GRUPO_FUNCAO...';


GO
ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO]
    ADD CONSTRAINT [PK_MNU_GRUPO_FUNCAO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[PEDIDOS]...';


GO
CREATE TABLE [dbo].[PEDIDOS] (
    [ID]                NUMERIC (18)    NOT NULL,
    [ID_USUARIO]        NUMERIC (18)    NOT NULL,
    [ID_PRODUTO]        NUMERIC (18)    NOT NULL,
    [ID_CAMPANHA]       NUMERIC (18)    NOT NULL,
    [QTD]               INT             NOT NULL,
    [VALOR_UNITARIO]    NUMERIC (18, 2) NOT NULL,
    [STATUS]            NVARCHAR (20)   NOT NULL,
    [COD_PAGAMENTO]     NVARCHAR (50)   NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30)   NULL,
    [DATA_INCLUSAO]     DATETIME        NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30)   NULL,
    [DATA_ALTERACAO]    DATETIME        NULL,
    [EXCLUIDO]          INT             NULL
);


GO
PRINT N'Creating PK_PEDIDOS...';


GO
ALTER TABLE [dbo].[PEDIDOS]
    ADD CONSTRAINT [PK_PEDIDOS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[PRODUTO]...';


GO
CREATE TABLE [dbo].[PRODUTO] (
    [ID]                NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (300)  NOT NULL,
    [ID_EMPRESA]        NUMERIC (18)    NOT NULL,
    [ID_TIPO]           NUMERIC (18)    NOT NULL,
    [ID_MARCA]          NUMERIC (18)    NOT NULL,
    [ID_CARACTERISTICA] NUMERIC (18)    NOT NULL,
    [COD_PRODUTO]       NVARCHAR (50)   NOT NULL,
    [VALOR_ORIGINAL]    NUMERIC (18, 2) NOT NULL,
    [PERCENT_DESCONTO]  NUMERIC (18, 2) NOT NULL,
    [DESCRICAO]         TEXT            NULL,
    [COMPOSICAO]        NVARCHAR (300)  NULL,
    [INST_LAVAGEM]      NVARCHAR (200)  NULL,
    [OBSERVACAO]        TEXT            NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50)   NULL,
    [DATA_INCLUSAO]     DATE            NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)   NULL,
    [DATA_ALTERACAO]    DATE            NULL,
    [EXCLUIDO]          INT             NULL
);


GO
PRINT N'Creating PK_PRODUTO...';


GO
ALTER TABLE [dbo].[PRODUTO]
    ADD CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[PRODUTO_CARACTERISTICA]...';


GO
CREATE TABLE [dbo].[PRODUTO_CARACTERISTICA] (
    [ID]                NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [QTD]               INT            NULL,
    [TAMANHO]           CHAR (3)       NULL,
    [COR]               NVARCHAR (20)  NULL,
    [REFERENCIAS]       NVARCHAR (300) NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50)  NULL,
    [DATA_INCLUSAO]     DATE           NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)  NULL,
    [DATA_ALTERACAO]    DATE           NULL,
    [EXCLUIDO]          INT            NULL
);


GO
PRINT N'Creating PK_PRODUTO_CARACTERISTICA...';


GO
ALTER TABLE [dbo].[PRODUTO_CARACTERISTICA]
    ADD CONSTRAINT [PK_PRODUTO_CARACTERISTICA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[PRODUTO_SUB_TIPO]...';


GO
CREATE TABLE [dbo].[PRODUTO_SUB_TIPO] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50) NULL,
    [ID_TIPO]           NUMERIC (18)  NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50) NULL,
    [DATA_INCLUSAO]     DATE          NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50) NULL,
    [DATA_ALTERACAO]    DATE          NULL,
    [EXCLUIDO]          INT           NULL
);


GO
PRINT N'Creating PK_PRODUTO_SUB_TIPO...';


GO
ALTER TABLE [dbo].[PRODUTO_SUB_TIPO]
    ADD CONSTRAINT [PK_PRODUTO_SUB_TIPO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[PRODUTO_TIPO]...';


GO
CREATE TABLE [dbo].[PRODUTO_TIPO] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50) NOT NULL,
    [SEXO]              NVARCHAR (10) NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50) NULL,
    [DATA_INCLUSAO]     DATE          NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50) NULL,
    [DATA_ALTERACAO]    DATE          NULL,
    [EXCLUIDO]          INT           NULL
);


GO
PRINT N'Creating PK_PRODUTO_TIPO...';


GO
ALTER TABLE [dbo].[PRODUTO_TIPO]
    ADD CONSTRAINT [PK_PRODUTO_TIPO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[RAMO_NEGOCIO]...';


GO
CREATE TABLE [dbo].[RAMO_NEGOCIO] (
    [ID]                NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [DESCRICAO]         NVARCHAR (255) NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (50)  NULL,
    [DATA_INCLUSAO]     DATETIME       NULL,
    [USUARIO_ALTERACAO] NVARCHAR (50)  NULL,
    [DATA_ALTERACAO]    DATETIME       NULL,
    [EXCLUIDO]          BIT            NULL
);


GO
PRINT N'Creating PK_RAMO_NEGOCIO...';


GO
ALTER TABLE [dbo].[RAMO_NEGOCIO]
    ADD CONSTRAINT [PK_RAMO_NEGOCIO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[REGIAO]...';


GO
CREATE TABLE [dbo].[REGIAO] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50) NOT NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30) NULL,
    [DATA_INCLUSAO]     DATETIME      NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30) NULL,
    [DATA_ALTERACAO]    DATETIME      NULL,
    [EXCLUIDO]          NUMERIC (18)  NULL
);


GO
PRINT N'Creating PK_REGIAO...';


GO
ALTER TABLE [dbo].[REGIAO]
    ADD CONSTRAINT [PK_REGIAO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[TIPO_CONTATO]...';


GO
CREATE TABLE [dbo].[TIPO_CONTATO] (
    [ID]        NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME_TIPO] NVARCHAR (50) NULL
);


GO
PRINT N'Creating PK_CONTATO_TIPO_CONTATO...';


GO
ALTER TABLE [dbo].[TIPO_CONTATO]
    ADD CONSTRAINT [PK_CONTATO_TIPO_CONTATO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating [dbo].[USUARIO]...';


GO
CREATE TABLE [dbo].[USUARIO] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [NOME]              NVARCHAR (50) NULL,
    [LOGIN]             NVARCHAR (50) NULL,
    [SENHA]             NVARCHAR (50) NULL,
    [ADM]               NUMERIC (18)  NULL,
    [ID_EMPRESA]        NUMERIC (18)  NULL,
    [ID_MNU_GRUPO]      NUMERIC (18)  NULL,
    [USUARIO_INCLUSAO]  NVARCHAR (30) NULL,
    [DATA_INCLUSAO]     DATETIME      NULL,
    [USUARIO_ALTERACAO] NVARCHAR (30) NULL,
    [DATA_ALTERACAO]    DATETIME      NULL,
    [EXCLUIDO]          NUMERIC (18)  NULL
);


GO
PRINT N'Creating PK_USUARIO...';


GO
ALTER TABLE [dbo].[USUARIO]
    ADD CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


GO
PRINT N'Creating DF_CAMPANHA_EXCLUIDO...';


GO
ALTER TABLE [dbo].[CAMPANHA]
    ADD CONSTRAINT [DF_CAMPANHA_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_CARRINHO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[CARRINHO]
    ADD CONSTRAINT [DF_CARRINHO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_CIDADES_EXCLUIDO...';


GO
ALTER TABLE [dbo].[CIDADES]
    ADD CONSTRAINT [DF_CIDADES_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_CONTATO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[CONTATO]
    ADD CONSTRAINT [DF_CONTATO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_CONTATO_PRINCIPAL...';


GO
ALTER TABLE [dbo].[CONTATO]
    ADD CONSTRAINT [DF_CONTATO_PRINCIPAL] DEFAULT ((0)) FOR [PRINCIPAL];


GO
PRINT N'Creating DF_CUPONS_CREDITO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[CUPONS_CREDITO]
    ADD CONSTRAINT [DF_CUPONS_CREDITO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_CUPONS_USUARIO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[CUPONS_USUARIO]
    ADD CONSTRAINT [DF_CUPONS_USUARIO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_EMPRESA_EXCLUIDO...';


GO
ALTER TABLE [dbo].[EMPRESA]
    ADD CONSTRAINT [DF_EMPRESA_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_MARCAS_EXCLUIDO...';


GO
ALTER TABLE [dbo].[MARCAS]
    ADD CONSTRAINT [DF_MARCAS_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_MNU_FUNCAO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[MNU_FUNCAO]
    ADD CONSTRAINT [DF_MNU_FUNCAO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_MNU_FUNCAO_NIVEL...';


GO
ALTER TABLE [dbo].[MNU_FUNCAO]
    ADD CONSTRAINT [DF_MNU_FUNCAO_NIVEL] DEFAULT ((0)) FOR [NIVEL];


GO
PRINT N'Creating DF_MNU_FUNCAO_SEPARADOR...';


GO
ALTER TABLE [dbo].[MNU_FUNCAO]
    ADD CONSTRAINT [DF_MNU_FUNCAO_SEPARADOR] DEFAULT ((0)) FOR [SEPARADOR];


GO
PRINT N'Creating DF_MNU_GRUPO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[MNU_GRUPO]
    ADD CONSTRAINT [DF_MNU_GRUPO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_MNU_GRUPO_FUNCAO_ALT...';


GO
ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO]
    ADD CONSTRAINT [DF_MNU_GRUPO_FUNCAO_ALT] DEFAULT ((1)) FOR [ALT];


GO
PRINT N'Creating DF_MNU_GRUPO_FUNCAO_EXC...';


GO
ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO]
    ADD CONSTRAINT [DF_MNU_GRUPO_FUNCAO_EXC] DEFAULT ((1)) FOR [EXC];


GO
PRINT N'Creating DF_MNU_GRUPO_FUNCAO_INC...';


GO
ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO]
    ADD CONSTRAINT [DF_MNU_GRUPO_FUNCAO_INC] DEFAULT ((1)) FOR [INC];


GO
PRINT N'Creating DF_PEDIDOS_EXCLUIDO...';


GO
ALTER TABLE [dbo].[PEDIDOS]
    ADD CONSTRAINT [DF_PEDIDOS_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_PRODUTO_INT_EXCLUIDO...';


GO
ALTER TABLE [dbo].[PRODUTO]
    ADD CONSTRAINT [DF_PRODUTO_INT_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_PRODUTO_CARACTERISTICA_INT_EXCLUIDO...';


GO
ALTER TABLE [dbo].[PRODUTO_CARACTERISTICA]
    ADD CONSTRAINT [DF_PRODUTO_CARACTERISTICA_INT_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_PRODUTO_SUB_TIPO_INT_EXCLUIDO...';


GO
ALTER TABLE [dbo].[PRODUTO_SUB_TIPO]
    ADD CONSTRAINT [DF_PRODUTO_SUB_TIPO_INT_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_PRODUTO_TIPO_INT_EXCLUIDO...';


GO
ALTER TABLE [dbo].[PRODUTO_TIPO]
    ADD CONSTRAINT [DF_PRODUTO_TIPO_INT_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_RAMO_NEGOCIO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[RAMO_NEGOCIO]
    ADD CONSTRAINT [DF_RAMO_NEGOCIO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating DF_REGIAO_EXCLUIDO...';


GO
ALTER TABLE [dbo].[REGIAO]
    ADD CONSTRAINT [DF_REGIAO_EXCLUIDO] DEFAULT ((0)) FOR [EXCLUIDO];


GO
PRINT N'Creating FK_AMIGOS_USUARIO...';


GO
ALTER TABLE [dbo].[AMIGOS] WITH NOCHECK
    ADD CONSTRAINT [FK_AMIGOS_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CAMPANHA_EMPRESA...';


GO
ALTER TABLE [dbo].[CAMPANHA] WITH NOCHECK
    ADD CONSTRAINT [FK_CAMPANHA_EMPRESA] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CARRINHO_CAMPANHA...';


GO
ALTER TABLE [dbo].[CARRINHO] WITH NOCHECK
    ADD CONSTRAINT [FK_CARRINHO_CAMPANHA] FOREIGN KEY ([ID_CAMPANHA]) REFERENCES [dbo].[CAMPANHA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CARRINHO_PRODUTO...';


GO
ALTER TABLE [dbo].[CARRINHO] WITH NOCHECK
    ADD CONSTRAINT [FK_CARRINHO_PRODUTO] FOREIGN KEY ([ID_PRODUTO]) REFERENCES [dbo].[PRODUTO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CARRINHO_USUARIO...';


GO
ALTER TABLE [dbo].[CARRINHO] WITH NOCHECK
    ADD CONSTRAINT [FK_CARRINHO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CIDADES_REGIAO...';


GO
ALTER TABLE [dbo].[CIDADES] WITH NOCHECK
    ADD CONSTRAINT [FK_CIDADES_REGIAO] FOREIGN KEY ([ID_REGIAO]) REFERENCES [dbo].[REGIAO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CONTATO_EMPRESA...';


GO
ALTER TABLE [dbo].[CONTATO] WITH NOCHECK
    ADD CONSTRAINT [FK_CONTATO_EMPRESA] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CONTATO_TIPO_CONTATO...';


GO
ALTER TABLE [dbo].[CONTATO] WITH NOCHECK
    ADD CONSTRAINT [FK_CONTATO_TIPO_CONTATO] FOREIGN KEY ([ID_TIPO_CONTATO]) REFERENCES [dbo].[TIPO_CONTATO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CUPONS_USUARIO_CUPONS_CREDITO...';


GO
ALTER TABLE [dbo].[CUPONS_USUARIO] WITH NOCHECK
    ADD CONSTRAINT [FK_CUPONS_USUARIO_CUPONS_CREDITO] FOREIGN KEY ([ID_CUPONS]) REFERENCES [dbo].[CUPONS_CREDITO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_CUPONS_USUARIO_USUARIO...';


GO
ALTER TABLE [dbo].[CUPONS_USUARIO] WITH NOCHECK
    ADD CONSTRAINT [FK_CUPONS_USUARIO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_EMPRESA_CIDADES...';


GO
ALTER TABLE [dbo].[EMPRESA] WITH NOCHECK
    ADD CONSTRAINT [FK_EMPRESA_CIDADES] FOREIGN KEY ([ID_CIDADE]) REFERENCES [dbo].[CIDADES] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_EMPRESA_RAMO_NEGOCIO...';


GO
ALTER TABLE [dbo].[EMPRESA] WITH NOCHECK
    ADD CONSTRAINT [FK_EMPRESA_RAMO_NEGOCIO] FOREIGN KEY ([ID_RAMO_NEGOCIO]) REFERENCES [dbo].[RAMO_NEGOCIO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_MNU_GRUPO_FUNCAO_MNU_FUNCAO...';


GO
ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO] WITH NOCHECK
    ADD CONSTRAINT [FK_MNU_GRUPO_FUNCAO_MNU_FUNCAO] FOREIGN KEY ([ID_MNU_FUNCAO]) REFERENCES [dbo].[MNU_FUNCAO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_MNU_GRUPO_FUNCAO_MNU_GRUPO...';


GO
ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO] WITH NOCHECK
    ADD CONSTRAINT [FK_MNU_GRUPO_FUNCAO_MNU_GRUPO] FOREIGN KEY ([ID_MNU_GRUPO]) REFERENCES [dbo].[MNU_GRUPO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PEDIDOS_CAMPANHA...';


GO
ALTER TABLE [dbo].[PEDIDOS] WITH NOCHECK
    ADD CONSTRAINT [FK_PEDIDOS_CAMPANHA] FOREIGN KEY ([ID_CAMPANHA]) REFERENCES [dbo].[CAMPANHA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PEDIDOS_PRODUTO...';


GO
ALTER TABLE [dbo].[PEDIDOS] WITH NOCHECK
    ADD CONSTRAINT [FK_PEDIDOS_PRODUTO] FOREIGN KEY ([ID_PRODUTO]) REFERENCES [dbo].[PRODUTO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PEDIDOS_USUARIO...';


GO
ALTER TABLE [dbo].[PEDIDOS] WITH NOCHECK
    ADD CONSTRAINT [FK_PEDIDOS_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PRODUTO_EMPRESA...';


GO
ALTER TABLE [dbo].[PRODUTO] WITH NOCHECK
    ADD CONSTRAINT [FK_PRODUTO_EMPRESA] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PRODUTO_MARCAS...';


GO
ALTER TABLE [dbo].[PRODUTO] WITH NOCHECK
    ADD CONSTRAINT [FK_PRODUTO_MARCAS] FOREIGN KEY ([ID_MARCA]) REFERENCES [dbo].[MARCAS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PRODUTO_PRODUTO_CARACTERISTICA...';


GO
ALTER TABLE [dbo].[PRODUTO] WITH NOCHECK
    ADD CONSTRAINT [FK_PRODUTO_PRODUTO_CARACTERISTICA] FOREIGN KEY ([ID_CARACTERISTICA]) REFERENCES [dbo].[PRODUTO_CARACTERISTICA] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PRODUTO_PRODUTO_TIPO...';


GO
ALTER TABLE [dbo].[PRODUTO] WITH NOCHECK
    ADD CONSTRAINT [FK_PRODUTO_PRODUTO_TIPO] FOREIGN KEY ([ID_TIPO]) REFERENCES [dbo].[PRODUTO_TIPO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
PRINT N'Creating FK_PRODUTO_SUB_TIPO_PRODUTO_TIPO...';


GO
ALTER TABLE [dbo].[PRODUTO_SUB_TIPO] WITH NOCHECK
    ADD CONSTRAINT [FK_PRODUTO_SUB_TIPO_PRODUTO_TIPO] FOREIGN KEY ([ID_TIPO]) REFERENCES [dbo].[PRODUTO_TIPO] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[AMIGOS] WITH CHECK CHECK CONSTRAINT [FK_AMIGOS_USUARIO];

ALTER TABLE [dbo].[CAMPANHA] WITH CHECK CHECK CONSTRAINT [FK_CAMPANHA_EMPRESA];

ALTER TABLE [dbo].[CARRINHO] WITH CHECK CHECK CONSTRAINT [FK_CARRINHO_CAMPANHA];

ALTER TABLE [dbo].[CARRINHO] WITH CHECK CHECK CONSTRAINT [FK_CARRINHO_PRODUTO];

ALTER TABLE [dbo].[CARRINHO] WITH CHECK CHECK CONSTRAINT [FK_CARRINHO_USUARIO];

ALTER TABLE [dbo].[CIDADES] WITH CHECK CHECK CONSTRAINT [FK_CIDADES_REGIAO];

ALTER TABLE [dbo].[CONTATO] WITH CHECK CHECK CONSTRAINT [FK_CONTATO_EMPRESA];

ALTER TABLE [dbo].[CONTATO] WITH CHECK CHECK CONSTRAINT [FK_CONTATO_TIPO_CONTATO];

ALTER TABLE [dbo].[CUPONS_USUARIO] WITH CHECK CHECK CONSTRAINT [FK_CUPONS_USUARIO_CUPONS_CREDITO];

ALTER TABLE [dbo].[CUPONS_USUARIO] WITH CHECK CHECK CONSTRAINT [FK_CUPONS_USUARIO_USUARIO];

ALTER TABLE [dbo].[EMPRESA] WITH CHECK CHECK CONSTRAINT [FK_EMPRESA_CIDADES];

ALTER TABLE [dbo].[EMPRESA] WITH CHECK CHECK CONSTRAINT [FK_EMPRESA_RAMO_NEGOCIO];

ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO] WITH CHECK CHECK CONSTRAINT [FK_MNU_GRUPO_FUNCAO_MNU_FUNCAO];

ALTER TABLE [dbo].[MNU_GRUPO_FUNCAO] WITH CHECK CHECK CONSTRAINT [FK_MNU_GRUPO_FUNCAO_MNU_GRUPO];

ALTER TABLE [dbo].[PEDIDOS] WITH CHECK CHECK CONSTRAINT [FK_PEDIDOS_CAMPANHA];

ALTER TABLE [dbo].[PEDIDOS] WITH CHECK CHECK CONSTRAINT [FK_PEDIDOS_PRODUTO];

ALTER TABLE [dbo].[PEDIDOS] WITH CHECK CHECK CONSTRAINT [FK_PEDIDOS_USUARIO];

ALTER TABLE [dbo].[PRODUTO] WITH CHECK CHECK CONSTRAINT [FK_PRODUTO_EMPRESA];

ALTER TABLE [dbo].[PRODUTO] WITH CHECK CHECK CONSTRAINT [FK_PRODUTO_MARCAS];

ALTER TABLE [dbo].[PRODUTO] WITH CHECK CHECK CONSTRAINT [FK_PRODUTO_PRODUTO_CARACTERISTICA];

ALTER TABLE [dbo].[PRODUTO] WITH CHECK CHECK CONSTRAINT [FK_PRODUTO_PRODUTO_TIPO];

ALTER TABLE [dbo].[PRODUTO_SUB_TIPO] WITH CHECK CHECK CONSTRAINT [FK_PRODUTO_SUB_TIPO_PRODUTO_TIPO];


GO
